# Generated by Django 4.2.3 on 2023-08-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0005_newspaper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newspaper',
            new_name='Newsletter',
        ),
    ]
